//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int Code { get; set; }
        public int CodeSource { get; set; }
        public int CodeDest { get; set; }
        public double Distance { get; set; }
        public int TypeDest { get; set; }
        public bool Nearest { get; set; }
        public Nullable<int> CodeShop { get; set; }
    
        public virtual Getaway Getaway { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
