//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopWayEntities : DbContext
    {
        public ShopWayEntities()
            : base("name=ShopWayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ConnectionGetAway> ConnectionGetAways { get; set; }
        public virtual DbSet<ConnectionStand> ConnectionStands { get; set; }
        public virtual DbSet<Getaway> Getaways { get; set; }
        public virtual DbSet<ProductShelf> ProductShelves { get; set; }
        public virtual DbSet<ProductShop> ProductShops { get; set; }
        public virtual DbSet<Shelf> Shelves { get; set; }
        public virtual DbSet<Stand> Stands { get; set; }
        public virtual DbSet<Wall> Walls { get; set; }
    }
}
