//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductShelf
    {
        public int Code { get; set; }
        public Nullable<int> CodeProduct { get; set; }
        public Nullable<int> CodeShelf { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shelf Shelf { get; set; }
    }
}
