//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shelf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shelf()
        {
            this.ProductShelves = new HashSet<ProductShelf>();
        }
    
        public int Code { get; set; }
        public Nullable<int> CodeStand { get; set; }
        public int Num { get; set; }
        public Nullable<int> CodeAlias { get; set; }
    
        public virtual Alias Alias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductShelf> ProductShelves { get; set; }
        public virtual Stand Stand { get; set; }
    }
}
